(define (problem starwars-delivery)
   (:domain starwars-transport)
   (:objects
       ilum dantooine coruscant naboo bespin pluto kessel luminara kepler-22b spira mandalore jupiter kamino ord-mantell malastare virabia geonosis yavin chopper v-4x bn-1 bb8 7-4x bt-1 q7-2k t3-m4 astromech-droid assassin-droid iz-100 k2so )
   (:init
      (planet ilum)
      (planet dantooine)
      (planet coruscant)
      (planet naboo)
      (planet bespin)
      (planet pluto)
      (planet kessel)
      (planet luminara)
      (planet kepler-22b)
      (planet spira)
      (planet mandalore)
      (planet jupiter)
      (planet kamino)
      (planet ord-mantell)
      (planet malastare)
      (planet virabia)
      (planet geonosis)
      (planet yavin)
      (droid chopper)
      (droid v-4x)
      (droid bn-1)
      (droid bb8)
      (droid 7-4x)
      (droid bt-1)
      (droid q7-2k)
      (droid t3-m4)
      (droid astromech-droid)
      (droid assassin-droid)
      (droid iz-100)
      (droid k2so)
      (ship-at naboo)
      (ship-free)
      (droid-at q7-2k virabia)
      (droid-at chopper kepler-22b)
      (droid-at v-4x malastare)
      (droid-at 7-4x mandalore)
      (droid-at t3-m4 mandalore)
      (droid-at bn-1 pluto)
      (droid-at astromech-droid geonosis)
      (droid-at bt-1 dantooine)
      (droid-at assassin-droid spira)
      (droid-at k2so bespin)
      (droid-at bb8 coruscant)
      (droid-at iz-100 dantooine)
   )
   (:goal
      (and
         (droid-at q7-2k kamino)
         (droid-at chopper bespin)
         (droid-at v-4x geonosis)
         (droid-at 7-4x kessel)
         (droid-at t3-m4 dantooine)
         (droid-at bn-1 ord-mantell)
         (droid-at astromech-droid jupiter)
         (droid-at bt-1 mandalore)
         (droid-at assassin-droid yavin)
         (droid-at k2so luminara)
         (droid-at bb8 ilum)
         (droid-at iz-100 bespin)
      )
   )
)
