(define (problem starwars-delivery)
   (:domain starwars-transport)
   (:objects
       jedha ezra togruta bendu scarif lothal zakuul ahch-to pluto dagobah jupiter narshadda nexus ord-mantell rutian tatooine mandalore bt-1 dj-8 c1-10p t3-m4 droideka security-droid d-0 droid-scout super-battle-droid 7-4x )
   (:init
      (planet jedha)
      (planet ezra)
      (planet togruta)
      (planet bendu)
      (planet scarif)
      (planet lothal)
      (planet zakuul)
      (planet ahch-to)
      (planet pluto)
      (planet dagobah)
      (planet jupiter)
      (planet narshadda)
      (planet nexus)
      (planet ord-mantell)
      (planet rutian)
      (planet tatooine)
      (planet mandalore)
      (droid bt-1)
      (droid dj-8)
      (droid c1-10p)
      (droid t3-m4)
      (droid droideka)
      (droid security-droid)
      (droid d-0)
      (droid droid-scout)
      (droid super-battle-droid)
      (droid 7-4x)
      (ship-at ord-mantell)
      (ship-free)
      (droid-at t3-m4 narshadda)
      (droid-at bt-1 lothal)
      (droid-at droideka jupiter)
      (droid-at droid-scout jedha)
      (droid-at super-battle-droid mandalore)
      (droid-at 7-4x nexus)
      (droid-at security-droid tatooine)
      (droid-at c1-10p zakuul)
      (droid-at dj-8 pluto)
      (droid-at d-0 togruta)
   )
   (:goal
      (and
         (droid-at t3-m4 rutian)
         (droid-at bt-1 pluto)
         (droid-at droideka zakuul)
         (droid-at droid-scout zakuul)
         (droid-at super-battle-droid bendu)
         (droid-at 7-4x ezra)
         (droid-at security-droid scarif)
         (droid-at c1-10p narshadda)
         (droid-at dj-8 ahch-to)
         (droid-at d-0 dagobah)
      )
   )
)
