(define (problem starwars-delivery)
   (:domain starwars-transport)
   (:objects
       pluto malastare nexus dantooine korriban ilum ord-mantell super-battle-droid q7-2k imperial-protocol-droid )
   (:init
      (planet pluto)
      (planet malastare)
      (planet nexus)
      (planet dantooine)
      (planet korriban)
      (planet ilum)
      (planet ord-mantell)
      (droid super-battle-droid)
      (droid q7-2k)
      (droid imperial-protocol-droid)
      (ship-at korriban)
      (ship-free)
      (droid-at q7-2k ord-mantell)
      (droid-at imperial-protocol-droid nexus)
      (droid-at super-battle-droid malastare)
   )
   (:goal
      (and
         (droid-at q7-2k dantooine)
         (droid-at imperial-protocol-droid pluto)
         (droid-at super-battle-droid ilum)
      )
   )
)
